BootcampLaravel/Week-4/final-project/dailyvegs/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index');
Route::get('/shop', 'FrontendController@shop');
Route::get('/about', 'FrontendController@about');
Route::get('/cart', 'FrontendController@cart');
Route::delete('/cart/{id}', 'OrdersController@destroy');
Route::post('/cart', 'OrdersController@store');
Route::get('/cart/{id}', 'FrontendController@cartshow');
Route::get('/be', function () {
    return view('backend.layouts.master');
});

Route::resource('/be/products', 'ProductsController');
Route::resource('/be/orders', 'OrdersController');

BootcampLaravel/Week-4/final-project/dailyvegs/app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    protected $table = "carts";
    protected $guarded = [];

    public function products(){
        return $this->hasMany('App\Product', 'product_id');
    }
}

BootcampLaravel/Week-4/final-project/dailyvegs/app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table = "orders";
    protected $guarded = [];
}

BootcampLaravel/Week-4/final-project/dailyvegs/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = "products";
    protected $guarded = [];
    
    public function cart(){
        return $this->belongsTo('App\Cart');
    }
}

BootcampLaravel/Week-4/final-project/dailyvegs/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

BootcampLaravel/Week-4/final-project/dailyvegs/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

BootcampLaravel/Week-4/final-project/dailyvegs/app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Product;
use App\Cart;


class FrontendController extends Controller
{
    public function index(){
        $products = DB::table('products')->get();
        return view('frontend.content.index', compact('products'));
    }

    public function shop(){
        $products = DB::table('products')->get();
        return view('frontend.content.shop', compact('products'));
    }

    public function about(){
        return view('frontend.content.about');
    }

    public function cart(){
        $carts = DB::table('carts')
        ->join('products', 'carts.product_id', '=', 'products.id')
        ->select('carts.id', 'carts.product_id', 'products.product_name', 'products.price')
        ->get();
        
        // $user = Cart::where('user_id', 1)->get();
        // // dd($user->all());
        // $carts = $user->products();

        // dd($carts->all());
        $total = DB::table('carts')
        ->join('products', 'carts.product_id', '=', 'products.id')
        ->sum('products.price');
        return view('frontend.content.cart', compact('carts', 'total'));
        dd($carts->all());
    }

    public function cartshow($id){
        $cart = new Cart;
        $cart->user_id = 1;
        $cart->product_id = $id;
        $cart->save();
        return redirect('/cart');
    }
}

BootcampLaravel/Week-4/final-project/dailyvegs/app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Order;
use App\Cart;

class OrdersController extends Controller
{
    public function index()
    {
        $orders = Order::all();
        return view('backend.content.orders.orders', compact('orders'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'address' => 'required',
            'phone' => 'required'
        ]);

        // dd($request->all());

        $orders = new Order;
        $orders->qty = 1;
        $orders->total = DB::table('carts')
                        ->join('products', 'carts.product_id', '=', 'products.id')
                        ->sum('products.price');
        $orders->name = $request["name"];
        $orders->address = $request["address"];
        $orders->phone = $request["phone"];
        $orders->status = "Belum Dikirim";
        $orders->user_id = 1;
        $orders->save();
        DB::table('carts')->delete();
        return redirect('/cart')->with('success', 'Order telah diterima');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        Cart::destroy($id);
        return redirect('/cart')->with('success', 'Product berhasil dihapus');
    }
}

BootcampLaravel/Week-4/final-project/dailyvegs/app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Product;

class ProductsController extends Controller
{
    public function index()
    {
        // $products = DB::table('products')->get();
        $products = Product::all();
        return view('backend.content.products.products', compact('products'));
    }

    public function create()
    {
        return view('backend.content.products.create');
    }

    public function store(Request $request)
    {
        // dd($request->all());
        $request->validate([
            'product_name' => 'required|unique:products',
            'price' => 'required|numeric'
        ]);
        
        $product = new Product;
        $product->product_name = $request["product_name"];
        $product->price = $request["price"];
        $product->save();
        return redirect('/be/products')->with('success', 'Product berhasil dibuat');
    }

    public function show($id)
    {
        $product = Product::find($id);
        return view('backend.content.products.show', compact('product'));
    }

    public function edit($id)
    {
        $product = Product::find($id);
        return view('backend.content.products.edit', compact('product'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'product_name' => 'required|unique:products',
            'price' => 'required|numeric'
        ]);
        
        $update = Product::where('id', $id)->update([
            "product_name" => $request["product_name"],
            "price" => $request["price"]
        ]);

        return redirect('/be/products')->with('success', 'Product berhasil diupdate');
    }

    public function destroy($id)
    {
        Product::destroy($id);
        return redirect('/be/products')->with('success', 'Product berhasil dihapus');
    }
}

BootcampLaravel/Week-4/final-project/dailyvegs/resources/views/backend/content/orders/orders.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card shadow mb-4">
   <div class="card-header py-3">
     <h3 class="m-0 font-weight-bold text-primary">Order List</h3>
   </div>
   <div class="card-body">
      @if(session('success'))
      <div class="alert alert-success" id="popup-success">
         {{ session('success')}}
      </div>
   @endif
   {{-- <a href="{{ route('products.create') }}" class="btn btn-primary btn-icon-split mb-2">
      <span class="icon text-white-50">
         <i class="fas fa-plus-circle"></i>
      </span>
      <span class="text">Create New Product</span>
    </a> --}}
   
   <table class="table table-bordered">
      <thead>
         <tr>
            <th style="width: 10px">#</th>
            <th>Order ID</th>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Status</th>
            <th style="width: 40px">Actions</th>
         </tr>
      </thead>
      <tbody>
         @forelse ($orders as $key => $order)
            <tr>
               <td> {{ $key+1 }}</td>
               <td> {{ $order -> id}} </td>
               <td> {{ $order -> name}}</td>
               <td> {{ $order -> address}}</td>
               <td> {{ $order -> phone}}</td>
               <td> {{ $order -> status}}</td>
               <td style="display: flex;"> <a href="/be/products/{{ $order->id }}" class="btn btn-info btn-sm">show</a>
               <a href="/be/products/{{ $order->id }}/edit" class="btn btn-default btn-sm">edit</a>
               </td>
            </tr>  
         @empty
            <tr>
               <td class="text-center" colspan="4">
                  No Data
               </td>
            </tr>
         @endforelse
      </tbody>
   </table>
   </div>
 </div>
    
@endsection

BootcampLaravel/Week-4/final-project/dailyvegs/resources/views/backend/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>DailyVegs Backoffice</title>

  <!-- Custom fonts for this template-->
  <link href="{{ asset('/sbadmin2/vendor/fontawesome-free/css/all.min.css' )}}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ asset('/sbadmin2/css/sb-admin-2.min.css') }}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    @include('backend.layouts.partials.sidebar')
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        @include('backend.layouts.partials.topbar')
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
          @yield('content')
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{{ asset('/sbadmin2/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ asset('/sbadmin2/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ asset('/sbadmin2/vendor/jquery-easing/jquery.easing.min.js')}}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ asset('/sbadmin2/js/sb-admin-2.min.js')}}"></script>

  <!-- script tambahan sweet alert, bukan dari bawaan sb-admin-2 -->
  @stack('scripts')
</body>

</html>

BootcampLaravel/Week-4/final-project/dailyvegs/resources/views/backend/layouts/partials/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

   <!-- Sidebar - Brand -->
   <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/be/">
     <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-leaf"></i>
     </div>
     <div class="sidebar-brand-text mx-3">DailyVegs</div>
   </a>

   <!-- Divider -->
   <hr class="sidebar-divider my-0">

   <!-- Divider -->
   <hr class="sidebar-divider">

   <!-- Heading -->
   <div class="sidebar-heading">
     Interface
   </div>

   <li class="nav-item">
      <a class="nav-link" href="{{route('products.index')}}">
         <i class="fas fa-database"></i>
         <span>Products</span></a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('orders.index')}}">
         <i class="fas fa-receipt"></i>
        <span>Orders</span></a>
    </li>

 </ul>

BootcampLaravel/Week-4/final-project/dailyvegs/resources/views/backend/layouts/partials/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

   <!-- Sidebar Toggle (Topbar) -->
   <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
     <i class="fa fa-bars"></i>
   </button>

   <!-- Topbar Search -->
   <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
     <div class="input-group">
       <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
       <div class="input-group-append">
         <button class="btn btn-primary" type="button">
           <i class="fas fa-search fa-sm"></i>
         </button>
       </div>
     </div>
   </form>

   <!-- Topbar Navbar -->
   <ul class="navbar-nav ml-auto">

     <!-- Nav Item - Search Dropdown (Visible Only XS) -->
     <li class="nav-item dropdown no-arrow d-sm-none">
       <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fas fa-search fa-fw"></i>
       </a>
       <!-- Dropdown - Messages -->
       <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
         <form class="form-inline mr-auto w-100 navbar-search">
           <div class="input-group">
             <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
             <div class="input-group-append">
               <button class="btn btn-primary" type="button">
                 <i class="fas fa-search fa-sm"></i>
               </button>
             </div>
           </div>
         </form>
       </div>
     </li>

     <!-- Nav Item - Alerts -->
     <li class="nav-item dropdown no-arrow mx-1">
       <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fas fa-bell fa-fw"></i>
         <!-- Counter - Alerts -->
         <span class="badge badge-danger badge-counter">3+</span>
       </a>
       <!-- Dropdown - Alerts -->
       <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
         <h6 class="dropdown-header">
           Alerts Center
         </h6>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="mr-3">
             <div class="icon-circle bg-primary">
               <i class="fas fa-file-alt text-white"></i>
             </div>
           </div>
           <div>
             <div class="small text-gray-500">December 12, 2019</div>
             <span class="font-weight-bold">A new monthly report is ready to download!</span>
           </div>
         </a>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="mr-3">
             <div class="icon-circle bg-success">
               <i class="fas fa-donate text-white"></i>
             </div>
           </div>
           <div>
             <div class="small text-gray-500">December 7, 2019</div>
             $290.29 has been deposited into your account!
           </div>
         </a>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="mr-3">
             <div class="icon-circle bg-warning">
               <i class="fas fa-exclamation-triangle text-white"></i>
             </div>
           </div>
           <div>
             <div class="small text-gray-500">December 2, 2019</div>
             Spending Alert: We've noticed unusually high spending for your account.
           </div>
         </a>
         <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
       </div>
     </li>

     <!-- Nav Item - Messages -->
     <li class="nav-item dropdown no-arrow mx-1">
       <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fas fa-envelope fa-fw"></i>
         <!-- Counter - Messages -->
         <span class="badge badge-danger badge-counter">7</span>
       </a>
       <!-- Dropdown - Messages -->
       <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
         <h6 class="dropdown-header">
           Message Center
         </h6>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="dropdown-list-image mr-3">
             <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
             <div class="status-indicator bg-success"></div>
           </div>
           <div class="font-weight-bold">
             <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
             <div class="small text-gray-500">Emily Fowler · 58m</div>
           </div>
         </a>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="dropdown-list-image mr-3">
             <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
             <div class="status-indicator"></div>
           </div>
           <div>
             <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
             <div class="small text-gray-500">Jae Chun · 1d</div>
           </div>
         </a>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="dropdown-list-image mr-3">
             <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
             <div class="status-indicator bg-warning"></div>
           </div>
           <div>
             <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
             <div class="small text-gray-500">Morgan Alvarez · 2d</div>
           </div>
         </a>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="dropdown-list-image mr-3">
             <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
             <div class="status-indicator bg-success"></div>
           </div>
           <div>
             <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
             <div class="small text-gray-500">Chicken the Dog · 2w</div>
           </div>
         </a>
         <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
       </div>
     </li>

     <div class="topbar-divider d-none d-sm-block"></div>

     <!-- Nav Item - User Information -->
     <li class="nav-item dropdown no-arrow">
       <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
         <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
       </a>
       <!-- Dropdown - User Information -->
       <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
         <a class="dropdown-item" href="#">
           <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
           Profile
         </a>
         <a class="dropdown-item" href="#">
           <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
           Settings
         </a>
         <a class="dropdown-item" href="#">
           <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
           Activity Log
         </a>
         <div class="dropdown-divider"></div>
         <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
           <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
           Logout
         </a>
       </div>
     </li>

   </ul>

 </nav>

BootcampLaravel/Week-4/final-project/dailyvegs/resources/views/frontend/content/about.blade.php
@extends('frontend.layouts.master')

@section('content')
<div class="hero-wrap hero-bread" style="background-image: url('{{ asset('/vegefoods/images/bg_1.jpg') }}');">
   <div class="container">
     <div class="row no-gutters slider-text align-items-center justify-content-center">
       <div class="col-md-9 ftco-animate text-center">
          <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>About us</span></p>
         <h1 class="mb-0 bread">About us</h1>
       </div>
     </div>
   </div>
 </div>

 <section class="ftco-section ftco-no-pb ftco-no-pt bg-light">
   <div class="container">
      <div class="row">
         <div class="col-md-5 p-md-5 img img-2 d-flex justify-content-center align-items-center" style="background-image: url({{ asset('/vegefoods/images/about.jpg') }});">
            <a href="https://vimeo.com/45830194" class="icon popup-vimeo d-flex justify-content-center align-items-center">
               <span class="icon-play"></span>
            </a>
         </div>
         <div class="col-md-7 py-5 wrap-about pb-md-5 ftco-animate">
       <div class="heading-section-bold mb-4 mt-md-5">
          <div class="ml-md-0">
            <h2 class="mb-4">Welcome to Vegefoods an eCommerce website</h2>
         </div>
       </div>
       <div class="pb-md-5">
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
               <p>But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
               <p><a href="/shop" class="btn btn-primary">Shop now</a></p>
            </div>
         </div>
      </div>
   </div>
</section>

@include('frontend.layouts.partials.testimony')
@include('frontend.layouts.partials.footer')
@endsection

BootcampLaravel/Week-4/final-project/dailyvegs/resources/views/frontend/content/cart.blade.php
@extends('frontend.layouts.master')

@section('content')
<div class="hero-wrap hero-bread" style="background-image: url('{{ asset('/vegefoods/images/bg_1.jpg') }}');">
   <div class="container">
     <div class="row no-gutters slider-text align-items-center justify-content-center">
       <div class="col-md-9 ftco-animate text-center">
          <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Cart</span></p>
         <h1 class="mb-0 bread">My Cart</h1>
       </div>
     </div>
   </div>
 </div>
 <section class="ftco-section ftco-cart">
   <div class="container">
      <div class="row">       
       <div class="col-md-12 ftco-animate">
          <div class="cart-list">
             <table class="table">
                <thead class="thead-primary">
                  <tr class="text-center">
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>Product name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    {{-- <th>Total</th> --}}
                  </tr>
                </thead>
                <tbody>
                  @if(session('success'))
                     <div class="alert alert-success" id="popup-success">
                        {{ session('success')}}
                     </div>
                  @endif
                  @foreach ($carts as $cart)
                  <tr class="text-center">
                        <td class="product-remove">
                           <form action="/cart/{{ $cart->id }}" method="post">
                              @csrf
                              @method('DELETE')
                           {{-- <a href="/cart/{{ $cart->id }}/delete"><span class="ion-ios-close"></span></a> --}}
                           <input type="submit" value="x" class="ion-ios-close">
                           </form>
                        </td>
                        
                     <td class="image-prod"><div class="img" style="background-image:url({{asset('/vegefoods/images/product-1.jpg')}});"></div></td>
                     
                     <td class="product-name">
                        <h3>{{$cart->product_name}}</h3>
                     </td>
                     
                     <td class="price" id="price">Rp {{number_format($cart->price,2)}}</td>
                     
                     <td class="quantity">
                        <div class="input-group mb-3">
                          <input type="text" id="qty" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100" disabled>
                       </div>
                     </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
           </div>
       </div>
    </div>
    <form action="/cart" class="info" method="POST">
      @csrf
    <div class="row justify-content-end">
       <div class="col-lg-8 mt-5 cart-wrap ftco-animate">
          <div class="cart-total mb-3">
             <h3>Shipping Information</h3>
             <p>Enter your destination</p>
              
           <div class="form-group">
              <label for="name">Name</label>
             <input type="text" name="name" class="form-control text-left px-3" placeholder="">
           </div>
           <div class="form-group">
              <label for="address">Address</label>
             <input type="text" name="address" class="form-control text-left px-3" placeholder="">
           </div>
           <div class="form-group">
              <label for="phone">Phone Number</label>
             <input type="text" name="phone" class="form-control text-left px-3" placeholder="">
           </div>
         
         </div>
       </div>
       <div class="col-lg-4 mt-5 cart-wrap ftco-animate">
          <div class="cart-total mb-3">
             <h3>Cart Totals</h3>
             <p class="d-flex total-price">
                  <span>Total</span>
                  <span id="total-full" name="total" class="font-weight-bold">Rp {{number_format($total,2)}}</span>
             </p>
             {{-- <p><a href="/cart/" class="btn btn-primary py-3 px-4">Checkout</a></p> --}}
             <button type="submit" class="btn btn-primary py-3 px-4">Checkout</button>
             {{-- TODO :change button --}}
          </div>
       </div>
      </form>
   </div>
   </div>
</section>
@endsection

BootcampLaravel/Week-4/final-project/dailyvegs/resources/views/frontend/layouts/partials/footer.blade.php
<hr>
<footer class="ftco-footer ftco-section">
   <div class="container">
      <div class="row">
         <div class="mouse">
               <a href="#" class="mouse-icon">
               <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
            </a>
         </div>
      </div>
     </div>
   </div>
 </footer>

<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>